<div class="zdb-toolbar-entry zsb-called-observers-details" data-name="called-observers">
    <div class="zdb-toolbar-preview boom" title="Called Observers">
        <div class="zdb-toolbar-icon"></div>
        <span class="zdb-toolbar-info">Called Observers JS</span>
    </div>
    <div class="zdb-toolbar-detail zdb-called-observers-detail-wrapper">
    	<div class="zdb-row zdb-toolbar-detail-header">
    		<div class="zdb-col-1-narrow">
    			<h1>Called Observers JS</h1>
    		</div>
    		<div class="zdb-col-3-wide">
    			<div class="zdb-pull-left">
    				<?php echo $this->devBarPager(); ?>
    			</div>
    			<div class="zdb-pull-right">
    				<ul class="zdb-toolbar-items zdb-horizontal">
    					<li class="zdb-toolbar-filter">
    						<label for="zdb-toolbar-input-filter-text">Filter by</label>
    						<select>
    							<option value="">Parameter</option>
    						</select>
    						<input type="text" name="zdb-toolbar-input-filter-text" id="zdb-toolbar-input-filter-text" size="6" class="zdb-toolbar-input zdb-toolbar-input-filter-parameter" />
    					</li>
    					<li class="zdb-toolbar-search">
    						<?php echo $this->devBarSearch(); ?>
    					</li>
    					<li>
							<div class="zdb-export-results-btn" title="Show Report"></div>
						</li>
    					<li class="zdb-toolbar-pin">
    						<div class="zdb-popup-pin" onclick="zendDevBar.unpin()"></div>
    					</li>
    				</ul>
    			</div>
    		</div>
    	</div>
    	<div class="zdb-row zdb-panel zsb-called-observers-panel">
    		<!-- Left panel: summary -->
    		<div class="zdb-col-1-narrow zdb-adaptive-height zdb-summary-table-wrapper zdb-called-observers-summary"></div>
    		
    		<!-- main panel: called-observers -->
    		<div class="zdb-col-3-wide zdb-entries-table-wrapper zdb-adaptive-height zsb-called-observers-table-wrapper"></div>
    	</div>
    </div>
</div>

<script type="text/javascript">
(function() {
	
})();
</script>